use crate::DEFAULT_INDEX_COLUMN_NAME;
use polars::prelude::{DataType, Schema};

// Constants for SQL Generation

/// The default SQL query, selected when the application starts or when examples are unavailable.
pub const DEFAULT_QUERY: &str = "\
-- Select all columns and rows
SELECT *
FROM AllData;
";

/// Column names potentially generated by Polars or common aggregation results
/// that are typically filtered out when searching for *source* columns for examples.
const COLS_FILTER_OUT: [&str; 14] = [
    DEFAULT_INDEX_COLUMN_NAME, // Default name from the index column feature
    "Average",
    "Frequency",
    "Total",
    "As Float",
    "Category",
    "Calculation Result",
    "Row Count",
    "Unique Values",
    "Minimum",
    "Maximum",
    "New Name for",
    "+ 10%",
    "DMY (day/month/year)", // Output of STRFTIME example
                            // Add other common aggregate/generated names here if needed
];

// --- Helper Functions ---

/// Checks if a column name should be filtered out from examples, either because
/// it's empty/whitespace or contains a known filtered substring.
fn is_filtered_col(name: &str) -> bool {
    let trimmed_name = name.trim();

    if trimmed_name.is_empty() {
        return true; // Filter empty/whitespace names
    }

    // Check if the column name CONTAINS any of the substrings to filter out.
    // The `any()` method stops checking as soon as it finds a match.
    COLS_FILTER_OUT
        .iter()
        .any(|substring| trimmed_name.contains(substring))
}

/// Finds the name of the Nth (0-based) column in the schema that matches a specified data type.
///
/// # Arguments
/// * `schema`: The DataFrame schema.
/// * `n`: The 0-based index (0 for first, 1 for second, etc.).
/// * `target_dtype`: A closure `Fn(&DataType) -> bool`.
///
/// # Returns
/// * `Some(&'a str)`: The name of the Nth matching column, borrowing from the schema.
/// * `None`: If fewer than N+1 columns satisfy the target_dtype.
fn find_nth_col_name(
    schema: &Schema,
    n: usize,
    target_dtype: impl Fn(&DataType) -> bool, // Closure defines the type check logic.
) -> Option<&str> {
    schema
        .iter()
        .filter(|(name, dtype)| !is_filtered_col(name.as_str()) && target_dtype(dtype))
        .nth(n) // nth(0) returns the first value, nth(1) the second, and so on.
        .map(|(name, _dtype)| name.as_str())
}

/// Generates a list of example SQL commands based on the provided DataFrame schema.
/// Uses helper functions to find suitable columns for demonstrating various SQL features.
pub fn sql_commands(schema: &Schema) -> Vec<String> {
    // Start with the default query
    let mut commands: Vec<String> = vec![DEFAULT_QUERY.to_string()];

    // --- target_dtypes for finding usable columns ---
    let is_any = |dtype: &DataType| !dtype.is_null(); // Find any non-null type column

    // Find first few usable columns of different types for examples
    let opt_str_col = find_nth_col_name(schema, 0, |dtype| dtype.is_string());
    let opt_int_col = find_nth_col_name(schema, 0, |dtype| dtype.is_integer());
    let opt_float_col = find_nth_col_name(schema, 0, |dtype| dtype.is_float());
    let opt_date_col = find_nth_col_name(schema, 0, |dtype| dtype.is_date());
    let opt_any_col = find_nth_col_name(schema, 0, is_any);
    let opt_any_col_1 = find_nth_col_name(schema, 1, is_any);
    let opt_any_col_2 = find_nth_col_name(schema, 2, is_any);

    // === SELECT Clause Examples ===

    // Example: LIMIT number of rows
    commands.push(
        "\
-- Limit the number of rows returned
SELECT *
FROM AllData
LIMIT 50;
"
        .to_string(),
    );

    // Example: Select specific columns
    if let (Some(col1), Some(col2)) = (opt_str_col, opt_int_col.or(opt_float_col)) {
        commands.push(format!(
            "\
-- Select specific columns by name
SELECT
    `{col1}`,
    `{col2}`
FROM AllData;
"
        ));
    }

    // Example: SELECT * with EXCEPT (Exclude)
    if let (Some(col1), Some(col2)) = (opt_any_col, opt_any_col_2) {
        commands.push(format!(
            "\
-- Select all columns EXCEPT specific ones
-- Useful for dropping temporary or unwanted columns
SELECT *
EXCEPT (
    `{col1}`,
    `{col2}`
)
FROM AllData;
"
        ));
    }

    // Example: SELECT * with RENAME
    if let (Some(col1), Some(col2)) = (opt_any_col, opt_any_col_1) {
        commands.push(format!(
            "\
-- Rename columns while preserving order
SELECT *
RENAME (
    `{col1}` AS `New Name for {col1}`,
    `{col2}` AS `New Name for {col2}`
)
FROM AllData;
"
        ));
    }

    // Example: SELECT * with REPLACE (Modify existing column's value)
    if let Some(float_col) = opt_float_col {
        commands.push(format!(
            "\
-- Replace values in a column with a calculation
-- Example: Increase float column `{float_col}` by 10%
SELECT *
REPLACE (
    `{float_col}` * 1.1 
    AS 
    `{float_col}`
)
FROM AllData;
"
        ));
    }

    // Example: Replacing a cell value
    if let Some(int_col) = opt_int_col {
        commands.push(format!(
            "\
-- Replaces cell values based on a condition
SELECT *
REPLACE (
    CASE
        -- Condition to identify the specific row
        WHEN `{int_col}` >= 10
        -- The new value for cells (some integer or string value)
        THEN 'New String Value'
        -- Keep the original values for all other rows in this column
        ELSE `{int_col}`
    -- Apply the result back to the original column name or another column
    END AS `{int_col}`
)
FROM AllData;
"
        ));
    }

    // Example: Add a NEW column using calculation
    if let (Some(col_f), Some(col_i)) = (opt_float_col, opt_int_col) {
        commands.push(format!(
            "\
-- Add a NEW calculated column 'Calculation Result'
-- Selects all original columns PLUS the new one
SELECT *,
       `{col_f}` * `{col_i}` 
       AS 
       `Calculation Result`
FROM AllData;
"
        ));
    }

    if let (Some(col1), Some(col2), Some(float_col)) = (opt_any_col, opt_any_col_1, opt_float_col) {
        commands.push(format!(
            "\
-- Except, Replace and Rename
SELECT *
EXCEPT (`{col1}`)
REPLACE (
    `{float_col}` * 1.1 
    AS 
    `{float_col}`
)
RENAME (
    `{float_col}` AS `{float_col} + 10%`,
    `{col2}` AS `New Name for {col2}`
)
FROM AllData;
"
        ));
    }

    // === Data Type Casting ===
    if let Some(int_col) = opt_int_col {
        commands.push(format!(
            "\
-- Explicitly CAST an integer column to FLOAT
SELECT *,
    CAST(`{int_col}` AS DOUBLE) AS `{int_col} As Float`
FROM AllData;
"
        ));
    }

    // === Conditional Logic (CASE WHEN) ===
    if let Some(num_col) = opt_int_col.or(opt_float_col) {
        commands.push(format!(
            "\
-- Create a new column based on conditions using CASE WHEN
SELECT *,
    CASE
        WHEN `{num_col}` > 100 THEN 'High'
        WHEN `{num_col}` > 10 THEN 'Medium'
        ELSE 'Low'
    END AS `{num_col} Category`
FROM AllData;
"
        ));
    }

    // === WHERE Clause Examples ===

    // Example: Filter by IS NULL / IS NOT NULL
    if let Some(col) = opt_any_col {
        commands.push(format!(
            "\
-- Filter rows where a column IS NULL or IS NOT NULL
SELECT *
FROM AllData
WHERE 
    `{col}` IS NULL;
-- Replace IS NULL with IS NOT NULL to get non-null rows
"
        ));
    }

    // Example: Filter by integer equality
    if let Some(int_col) = opt_int_col {
        commands.push(format!(
            "\
-- Filter rows where a numeric column equals a specific value
-- number comparisons: =, >, <, >=, <=, !=
SELECT *
FROM AllData
WHERE 
    `{int_col}` = 2024;
-- Or filter by an (inclusive) range of values:    
-- WHERE `{int_col}` BETWEEN 2020 AND 2024
-- Or filter based on a list of values using IN:
-- WHERE `{int_col}` IN (2020, 2022, 2024)
"
        ));
    }

    // Example: Filter by string equality and LIKE
    if let Some(str_col) = opt_str_col {
        commands.push(format!(
            "\
-- Filter rows based on string content
SELECT *
FROM AllData
WHERE 
    `{str_col}` = 'Specific Value';
-- Or using LIKE for pattern matching (case-sensitive)
-- WHERE `{str_col}` LIKE 'Prefix%';
-- WHERE `{str_col}` LIKE '%Middle%';
-- WHERE `{str_col}` LIKE '%Suffix';
-- Use ILIKE for case-insensitive matching
-- WHERE `{str_col}` ILIKE 'pattern%';
-- Or filter based on a list of values using IN:
-- WHERE `{str_col}` IN ('Value A', 'Value B')
"
        ));
    }

    // Example: Filter using AND / OR
    if let (Some(int_col), Some(str_col)) = (opt_int_col, opt_str_col) {
        commands.push(format!(
            "\
-- Combine multiple filter conditions using AND / OR
SELECT *
FROM AllData
WHERE 
    `{int_col}` >= 2024
AND 
    `{str_col}` != 'Exclude This'
-- Or filter based on a list of values using IN:
-- WHERE `{int_col}` IN (2020, 2022, 2024)
-- WHERE `{str_col}` IN ('Value A', 'Value B')
"
        ));
    }

    // === ORDER BY and LIMIT Examples ===

    // Example: ORDER BY multiple columns
    if let (Some(col1), Some(col2)) = (opt_str_col, opt_int_col.or(opt_float_col)) {
        commands.push(format!(
            "\
-- Sort results by a single column (ASC default, or DESC) or            
-- Sort results by multiple columns (precedence based on order)
SELECT *
FROM AllData
ORDER BY
    `{col1}` ASC, -- Primary sort key
    `{col2}` DESC; -- Secondary sort key
"
        ));
    }

    // === GROUP BY Examples ===

    // Example: Simple GROUP BY with COUNT
    if let (Some(col1), Some(col2)) = (
        opt_date_col.or(opt_int_col).or(opt_str_col).or(opt_any_col),
        opt_any_col_2,
    ) {
        // Use first (date or int or any) as category
        commands.push(format!(
            "\
-- Count rows per category (Frequency)
SELECT
    `{col1}`,
    `{col2}`,
    COUNT(*) AS Frequency
FROM AllData
GROUP BY 
    `{col1}`,
    `{col2}`
ORDER BY
    Frequency DESC;
"
        ));
    }

    // Example: GROUP BY with SUM
    if let (Some(cat_col), Some(num_col)) = (opt_str_col, opt_int_col.or(opt_float_col)) {
        commands.push(format!(
            "\
-- Calculate SUM of a numeric column per category
SELECT
    `{cat_col}`,
    SUM(`{num_col}`) AS `{num_col} Total`
FROM AllData
GROUP BY 
    `{cat_col}`
ORDER BY 
    `{num_col} Total` DESC;
"
        ));
    }

    // Example: GROUP BY with multiple aggregates (COUNT, SUM, AVG, MIN, MAX)
    if let (Some(cat_col), Some(val_col)) = (opt_str_col, opt_int_col.or(opt_float_col)) {
        commands.push(format!(
            "\
-- Calculate multiple aggregate functions per category
SELECT
    `{cat_col}`,
    -- Total rows per category
    COUNT(*) AS `Row Count`,
    -- Count unique values in `{val_col}`:
    COUNT(DISTINCT `{val_col}`) AS `Unique Values`,
    SUM(`{val_col}`) AS Total,     -- Sum of val_col
    AVG(`{val_col}`) AS Average,   -- Average of val_col
    MIN(`{val_col}`) AS Minimum,   -- Minimum value
    MAX(`{val_col}`) AS Maximum    -- Maximum value
FROM AllData
GROUP BY
    `{cat_col}`
ORDER BY
    `Row Count` DESC;
"
        ));
    }

    // Example: HAVING clause (Filter *after* aggregation)
    if let (Some(cat_col), Some(val_col)) = (opt_str_col, opt_int_col.or(opt_float_col)) {
        commands.push(format!(
            "\
-- Use HAVING to filter groups based on aggregate results
SELECT
    `{cat_col}`,
    AVG(`{val_col}`) AS `{val_col} Average`
FROM AllData
GROUP BY
    `{cat_col}`
HAVING
    -- Only show categories where the average > 1000
    `{val_col} Average` > 1000
ORDER BY
    `{val_col} Average` DESC;
"
        ));
    }

    // === Date/Time Functions ===

    // Example: Format date column
    if let Some(date_col) = opt_date_col {
        commands.push(format!(
            "\
-- Format a date column into DD/MM/YYYY using STRFTIME
SELECT *, -- Select all original columns
    STRFTIME(`{date_col}`, '%d/%m/%Y') AS `DMY (day/month/year)`
FROM AllData
ORDER BY 
    `{date_col}`;
"
        ));
    }

    // --- Final command (often useful) ---
    if let (Some(col1), Some(col2)) = (opt_any_col, opt_any_col_2) {
        commands.push(format!(
            "\
-- Show distinct values of a column
SELECT DISTINCT 
    `{col1}`,
    `{col2}`,
FROM AllData
ORDER BY 
    `{col2}`;
"
        ));
    }

    commands
}
